/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/Signin'
import { Route as OrdersRouteImport } from './routes/Orders'
import { Route as OrderRouteImport } from './routes/Order'
import { Route as HomeRouteImport } from './routes/Home'
import { Route as BookingsRouteImport } from './routes/Bookings'
import { Route as IndexRouteImport } from './routes/index'

const SigninRoute = SigninRouteImport.update({
  id: '/Signin',
  path: '/Signin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/Orders',
  path: '/Orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/Order',
  path: '/Order',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/Home',
  path: '/Home',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/Bookings',
  path: '/Bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Bookings': typeof BookingsRoute
  '/Home': typeof HomeRoute
  '/Order': typeof OrderRoute
  '/Orders': typeof OrdersRoute
  '/Signin': typeof SigninRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Bookings': typeof BookingsRoute
  '/Home': typeof HomeRoute
  '/Order': typeof OrderRoute
  '/Orders': typeof OrdersRoute
  '/Signin': typeof SigninRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Bookings': typeof BookingsRoute
  '/Home': typeof HomeRoute
  '/Order': typeof OrderRoute
  '/Orders': typeof OrdersRoute
  '/Signin': typeof SigninRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Bookings' | '/Home' | '/Order' | '/Orders' | '/Signin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Bookings' | '/Home' | '/Order' | '/Orders' | '/Signin'
  id:
    | '__root__'
    | '/'
    | '/Bookings'
    | '/Home'
    | '/Order'
    | '/Orders'
    | '/Signin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  HomeRoute: typeof HomeRoute
  OrderRoute: typeof OrderRoute
  OrdersRoute: typeof OrdersRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Signin': {
      id: '/Signin'
      path: '/Signin'
      fullPath: '/Signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Orders': {
      id: '/Orders'
      path: '/Orders'
      fullPath: '/Orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Order': {
      id: '/Order'
      path: '/Order'
      fullPath: '/Order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Home': {
      id: '/Home'
      path: '/Home'
      fullPath: '/Home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Bookings': {
      id: '/Bookings'
      path: '/Bookings'
      fullPath: '/Bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  HomeRoute: HomeRoute,
  OrderRoute: OrderRoute,
  OrdersRoute: OrdersRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
